### PR TITLE
Fix qm.WithDeleted helper with a custom soft delete column

### LINKED ISSUE #1256: Using `auto-columns.deleted` config and `qm.WithDeleted()`
### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v4.13.0

### What is your database and version (eg. Postgresql 10)
cockroach v22.2.6

### If this happened at generation time what was the full SQLBoiler command you used to generate your models? (if not applicable leave blank)
```
sqlboiler --wipe --no-hooks --no-rows-affected --no-tests --add-soft-deletes -p crdb -o crdb crdb
```

### Please provide a relevant database schema so we can replicate your issue (Provided you are comfortable sharing this)

```sql
CREATE TABLE IF NOT EXISTS kitties (
    id
        CHAR(26) NOT NULL,
    delete_time
        TIMESTAMPZ NULL
);
```

**sqlboiler.yaml**
```
crdb:
  user: user
  pass: password
  host: localhost
  port: 26257
  dbname: 'app'
  sslmode: disable
auto-columns:
  deleted: 'delete_time'
```

### Further information. What did you do, what did you expect?
Hello,
the problem that I have is that when I try to generate everything and I use it, the query modifier `qm.WithDeleted()` doesn't remove the part that is `AND ("kitties"."delete_time" is null)` in the SQL query. I checked it with the `boil.DebugMode = true`.

If I use the default `auto-columns.deleted` setting and modify my schema from `delete_time` to `deleted_at`, it works as expected.

I reivewed the code inside the repo and I saw that is because the `deleted_at` is hardcoded in the code instead of read it from the config (this commit is actually the HEAD of master).
https://github.com/volatiletech/sqlboiler/blob/66cb4680047d7801156a080ba69a3f14ef5986fc/queries/query.go#L411 

If the bug exists, any workaround in the meantime?

Thanks

### PR DESCRIPTION
**Pull request by lopezator**
As the `deletedAtRgx` was hardcoded, there wasn't way to use the `qm.WithDeleted` helper when you have a custom soft delete column set in `auto-columns.deleted` config.

This PR fixes that, overwriting the variable when the the custom column is set and the soft deletion capatibilies are activated for that table.

Closes #1256

### CODE REVIEW

File: templates/main/13_all.go.tpl [hunk 1]
```diff
@@ -13,6 +13,9 @@ func {{$alias.UpPlural}}(mods ...qm.QueryMod) {{$alias.DownSingular}}Query {
     if len(queries.GetSelect(q)) == 0 {
         queries.SetSelect(q, []string{"{{$schemaTable}}.*"})
     }
+    {{if and .AddSoftDeletes $canSoftDelete .AutoColumns.Deleted -}}
+        queries.SetRemoveSoftDeleteRgx(removeSoftDeleteRgx)
+    {{end}}
```
Comment (stephenafamo) [inline templates/main/13_all.go.tpl:18]: This should be in a singleton template. It only needs to be called once. here it will be called for every table.

File: templates/main/singleton/boil_queries.go.tpl [hunk 2]
```diff
@@ -12,6 +12,13 @@ var dialect = drivers.Dialect{
 	UseCaseWhenExistsClause: {{.Dialect.UseCaseWhenExistsClause}},
 }
 
+{{if not .AutoColumns.Deleted}}
+    // This is a dummy variable to prevent unused regexp import error
+    var _ = &regexp.Regexp{}
+{{else}}
+    var removeSoftDeleteRgx = regexp.MustCompile("{{$.AutoColumns.Deleted}}[\"'`]? is null")
+{{- end}}
```
Comment (stephenafamo) [inline templates/main/singleton/boil_queries.go.tpl:20]: This would be better alongside other global variables which are a little after the model definition.

**Review by stephenafamo — CHANGES_REQUESTED** [review]
Thanks for this. Looks like a good implementation

File: templates/main/singleton/boil_queries.go.tpl (hunk 2 above)
Comment (lopezator) [reply templates/main/singleton/boil_queries.go.tpl:20]: What do you exactly mean by `model`? The table's corresponding struct? Do you mean to have the variable replicated inside each table's generated file? Like here?

https://github.com/volatiletech/sqlboiler/blob/ca0d71ed51bab25289fb52dd217df8a4ffd859dc/templates/main/01_types.go.tpl#L45-L61

Would it make sense to set this globally in an `init()` function inside some singleton template? Create a new one for this use cases?

Comment (stephenafamo) [reply templates/main/singleton/boil_queries.go.tpl:20]: > Would it make sense to set this globally in an `init()` function inside some singleton template? Create a new one for this use cases?

I mixed some stuff up. I think that would be the best solution for the current architecture, but this will break down if there are multiple generated models with different `deleted` columns, since they will all change the global `rgx` and whichever is last will win.

In a hypothetical `v5` the query mod to remove `deleted_at` should move into generated code, but that would need some changes to the query object.

File: templates/main/13_all.go.tpl (hunk 1 above)
Comment (lopezator) [reply templates/main/13_all.go.tpl]: It makes sense, changed!

**Comment by lopezator** [comment]
@stephenafamo Thanks for the quick review! I simplified the things a bit, let me know what you think :slightly_smiling_face:

File: templates/main/singleton/boil_queries.go.tpl (hunk 2 above)
Comment (lopezator) [reply templates/main/singleton/boil_queries.go.tpl]: >  In a hypothetical v5 the query mod to remove deleted_at should move into generated code

I agree! Should I open a new issue labeled for v5 and so we can go over it later?

Comment (stephenafamo) [reply templates/main/singleton/boil_queries.go.tpl]: Yes, that would be nice. Also if making any changes, send the PR to the `v5` branch.

Comment (lopezator) [reply templates/main/singleton/boil_queries.go.tpl]: Gotcha! :+1:

File: templates/main/singleton/boil_queries.go.tpl [hunk 3]
```diff
@@ -12,10 +12,18 @@ var dialect = drivers.Dialect{
...
+    var _ = &regexp.Regexp{}
+{{- end}}
+
 // NewQuery initializes a new Query using the passed in QueryMods
 func NewQuery(mods ...qm.QueryMod) *queries.Query {
 	q := &queries.Query{}
 	queries.SetDialect(q, &dialect)
+	{{- if and (.AutoColumns.Deleted) (ne $.AutoColumns.Deleted "deleted_at") }}
+		queries.SetRemoveSoftDeleteRgx(regexp.MustCompile("{{$.AutoColumns.Deleted}}[\"'`]? is null"))
+	{{- end }}
```
Comment (stephenafamo) [inline templates/main/singleton/boil_queries.go.tpl:26]: I think just using an init function would be better. This would call the `SetRemoveSoftDeleteRgx` every time a new query is created.

Comment (lopezator) [reply templates/main/singleton/boil_queries.go.tpl]: Right! Changed :)

**Comment by lopezator** [comment]
Changes made, PTAL @stephenafamo :slightly_smiling_face:

**Review by stephenafamo — APPROVED** [review]

**Comment by lopezator** [comment]
Thank your for all the support and responsiveness @stephenafamo !! Btw are you planning to release a bugfix release anytime soon? Thanks again 🙏.
